### ISSUE TITLE
maybe rearrange the folders

### ISSUE THREAD

**Issue by Alexey-T** [iLya2IK/wchttpserver#4]
It would be nice to have the

- src (or 'source') folder for .pas/.inc files (except for demo)
- docs folder for Markdown/text files
- icons folder for PNG/SVG icons

.lpk of project can be inside 'src',
while demo project should be in its own folder.

**Comment by iLya2IK** [comment]
The structure of the project has been put in order. Lpk file added

**Comment by Alexey-T** [comment]
great, tkx.
