### ISSUE TITLE
maybe add some 'prefix' to src files

### ISSUE THREAD

**Issue by Alexey-T** [iLya2IK/wchttpserver#5]
I like prefixed filenames, so I suggest some prefix like 'wc_' or 'wc' or 'wchttp_'.
also 2 files have not prefixed names:
abstracthttpserver.pas
custabshttpapp.pas

**Comment by iLya2IK** [comment]
Я немного изменил файловую структуру проекта - выделил модули с абстрактными классами в отдельную папку fpwebabstract. Файлы с константами и низкоуровневыми процедурами для работы с протоколами перенес в protocols. Остальные файлы получили префикс wc

**Comment by Alexey-T** [comment]
отлично, спасибо.
